BOOTLOADER = atmel-dfu
SPLIT_KEYBOARD = no
RGBLIGHT_ENABLE = no
# RGB_MATRIX_ENABLE = no
MOUSEKEY_ENABLE = yes
CONSOLE_ENABLE = no

# reduce filesize
# COMMAND_ENABLE = no
# EXTRAFLAGS += -flto

CUSTOM_ONESHOT_ENABLE = yes
CUSTOM_SWAPPER_ENABLE = yes
CUSTOM_REPEAT_ENABLE = yes
CUSTOM_CAPS_WORD_ENABLE = yes
# COMBO_ENABLE = yes
