SRC += encoders.c

# Disable unused features
VIA_ENABLE = no
NKRO_ENABLE = no
AUDIO_ENABLE = no
STENO_ENABLE = no
COMMAND_ENABLE = no
TERMINAL_ENABLE = no
KEY_LOCK_ENABLE = no
BOOTMAGIC_ENABLE = no
SLEEP_LED_ENABLE = no
TAP_DANCE_ENABLE = no
VELOCIKEY_ENABLE = no
SWAP_HANDS_ENABLE = no

SPACE_CADET_ENABLE = no
KEY_OVERRIDE_ENABLE = no

LEADER_ENABLE = no
MOUSEKEY_ENABLE = yes
CUSTOM_ONESHOT_ENABLE = no
CUSTOM_SWAPPER_ENABLE = yes
CUSTOM_REPEAT_ENABLE = no
CUSTOM_CAPS_WORD_ENABLE = no
COMBO_ENABLE = no
