# BOOTLOADER = atmel-dfu
SPLIT_KEYBOARD = no
MOUSEKEY_ENABLE = yes
CONSOLE_ENABLE = no
BOOTMAGIC_ENABLE = yes
# RGBLIGHT_ENABLE = no

# reduce filesize
# COMMAND_ENABLE = no
# EXTRAFLAGS += -flto

COMBO_ENABLE = no
CUSTOM_ONESHOT_ENABLE = yes
CUSTOM_SWAPPER_ENABLE = yes
CUSTOM_REPEAT_ENABLE = yes
CUSTOM_CAPS_WORD_ENABLE = yes
