# BOOTLOADER = atmel-dfu
SPLIT_KEYBOARD = no

CONSOLE_ENABLE = no
BOOTMAGIC_ENABLE = no

# reduce filesize
# COMMAND_ENABLE = no
# EXTRAFLAGS += -flto

MOUSEKEY_ENABLE = yes
COMBO_ENABLE = yes
CUSTOM_ONESHOT_ENABLE = yes
CUSTOM_SWAPPER_ENABLE = yes
CUSTOM_REPEAT_ENABLE = yes
CUSTOM_CAPS_WORD_ENABLE = yes
