# BOOTLOADER = atmel-dfu
SPLIT_KEYBOARD = no
RGBLIGHT_ENABLE = no
# oRGB_MATRIX_ENABLE = no
MOUSEKEY_ENABLE = yes
CONSOLE_ENABLE = no
BOOTMAGIC_ENABLE = yes

# reduce filesize
# COMMAND_ENABLE = no
# EXTRAFLAGS += -flto

COMBO_ENABLE = yes
CUSTOM_ONESHOT_ENABLE = yes
CUSTOM_SWAPPER_ENABLE = yes
CUSTOM_REPEAT_ENABLE = yes
CUSTOM_CAPS_WORD_ENABLE = yes
