SRC += deanbot.c

# BOOTLOADER = atmel-dfu
# SPLIT_KEYBOARD = no

# Disable unused features
CONSOLE_ENABLE = no
VIA_ENABLE = no
NKRO_ENABLE = no
AUDIO_ENABLE = no
STENO_ENABLE = no
COMMAND_ENABLE = no
UNICODE_ENABLE = no
TERMINAL_ENABLE = no
KEY_LOCK_ENABLE = no
BOOTMAGIC_ENABLE = no
SLEEP_LED_ENABLE = no
TAP_DANCE_ENABLE = no
VELOCIKEY_ENABLE = no
SWAP_HANDS_ENABLE = no
SPACE_CADET_ENABLE = no
KEY_OVERRIDE_ENABLE = no
CASEMODES_ENABLE = no
GRAVE_ESC_ENABLE = no

BACKLIGHT_ENABLE = no
# RGBLIGHT_ENABLE = no
# RGB_MATRIX_ENABLE = no

COMBO_ENABLE = yes
LEADER_ENABLE = yes
MOUSEKEY_ENABLE = yes
CUSTOM_ONESHOT_ENABLE = yes
CUSTOM_SWAPPER_ENABLE = yes
CUSTOM_REPEAT_ENABLE = noj
CUSTOM_CAPS_WORD_ENABLE = yes

VPATH += keyboards/gboards/

ifeq ($(strip $(CUSTOM_ONESHOT_ENABLE)), yes)
	SRC += ./features/oneshot.c
	OPT_DEFS += -DCUSTOM_ONESHOT_ENABLE
endif

ifeq ($(strip $(CUSTOM_REPEAT_ENABLE)), yes)
	SRC += ./features/repeat.c
	OPT_DEFS += -DCUSTOM_REPEAT_ENABLE
endif

ifeq ($(strip $(CUSTOM_CAPS_WORD_ENABLE)), yes)
	SRC += ./features/caps_word.c
	OPT_DEFS += -DCUSTOM_CAPS_WORD_ENABLE
endif

ifeq ($(strip $(CUSTOM_SWAPPER_ENABLE)), yes)
	SRC += ./features/swapper.c
	OPT_DEFS += -DCUSTOM_SWAPPER_ENABLE
endif
